version: "3.8"

services:
  serverprog:
    image: serverprog:v1
    container_name: serverprog
    build:
      context: .
      dockerfile: Dockerfile
      target: final-app
    ports:
      - "7000:80"     
      - "7001:443"
    environment:
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: 7001
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/cert.pfx
      ASPNETCORE_Kestrel__Certificates__Default__Password: "Passw0rd"
      ASPNETCORE_ENVIRONMENT: Development
      ApiBaseAddress: "https://webapi:443" 
    volumes:
      - ${USERPROFILE}/.aspnet/https:/https/
      - serverprog-data:/app/data
      - serverprog-keys:/app/keys
    depends_on:
      - webapi 
    networks:
      - serverprog-network

  webapi:
    image: webapi:v1
    container_name: webapi
    build:
      context: .         
      dockerfile: Dockerfile
      target: final-api
    ports:
      - "7002:80"             
      - "7003:443"            
    environment:
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: 7003
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/cert.pfx
      ASPNETCORE_Kestrel__Certificates__Default__Password: "Passw0rd"
      ASPNETCORE_ENVIRONMENT: Development
    volumes:
      - ${USERPROFILE}/.aspnet/https:/https/
      - webapi-data:/app/data
      - webapi-keys:/app/keys
    networks:
      - serverprog-network

networks:
  serverprog-network:
    driver: bridge

volumes:
  serverprog-data:
  serverprog-keys:
  webapi-data:
  webapi-keys:
